APT {
    FTPArchive {
        Release {
            Origin "Λ7M | Repo";
            Label "Λ7M | Repo";
            Suite stable;
            Version 1.0;
            Codename "ios";
            Architectures "iphoneos-arm" "iphoneos-arm64" "iphoneos-arm64e";
            Components main;
            Description "Λ7M Personal iOS Tweaks Repository";
        };
    };
};